import { cp, mkdir, readFile, readdir, rename, unlink, writeFile } from "node:fs/promises";
import { existsSync, readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { SessionManager, type ExtensionAPI, type ExtensionContext } from "@earendil-works/pi-coding-agent";
import { Text } from "@earendil-works/pi-tui";
import { Type } from "typebox";
import YAML from "yaml";
import { branchName, createWorkflow, isPlanPhaseCommand, isReadOnlyPhaseCommand, slugify, transition, type Phase, type WorkflowState } from "./workflow-core.ts";

const PACKAGE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const FLOW_DIR = path.join(".pi", "harness");
const ONBOARDING_FILE = path.join(FLOW_DIR, "onboarding-proposal.json");
const REQUIRED_PI_PACKAGES = ["npm:@gotgenes/pi-permission-system@20.3.0"];
const KINDS: Record<string, string[]> = {
  Decision: ["Context", "Decision", "Alternatives", "Consequences", "Relations"],
  Plan: ["Context", "Scope", "Projects", "Contracts", "Acceptance criteria", "Validation", "Open questions", "Relations"],
  Task: ["Context", "Steps", "Current state", "Blockers", "Relations"],
  Contract: ["Context", "Owner", "Consumers", "Compatibility", "Validation", "Relations"],
  Reference: ["Context", "Observations", "Relations"],
};
type Manifest = { workspace?: { docs_directory?: string; projects_directory?: string; worktrees_directory?: string; setup?: string[]; cleanup?: string[] }; agents?: Record<string, { model?: string }>; subagents?: { async_by_default?: boolean; tool_description_mode?: "full" | "compact" | "custom"; completion_batch?: boolean; intercom_bridge_mode?: "always" | "fork-only" | "off"; supervisor_output?: "compact" | "full" }; pi?: { packages?: string[] }; permissions?: { default?: "allow" | "ask" | "deny"; shell?: "allow" | "ask" | "deny"; mcp?: "allow" | "ask" | "deny"; external_directories?: "allow" | "ask" | "deny" }; code_graph?: { server_name?: string; command?: string; args?: string[]; lifecycle?: string; idle_timeout?: number }; projects?: Array<{ name: string; path: string; repository?: string; default_branch?: string; depends_on?: string[]; ci?: string[]; setup?: string[]; cleanup?: string[] }> };

function isWorker() { return process.env.PI_SUBAGENT_CHILD === "1" && ["impl", "impl-lite"].includes(process.env.PI_SUBAGENT_CHILD_AGENT ?? ""); }
function isSubagent() { return process.env.PI_SUBAGENT_CHILD === "1"; }
function sessionId(ctx: ExtensionContext) { return process.env.PI_SUBAGENT_PARENT_SESSION || ctx.sessionManager.getSessionId() || "ephemeral"; }
function findRoot(cwd: string) { let current = path.resolve(cwd); while (true) { if (existsSync(path.join(current, "workspace.yaml"))) return current; const parent = path.dirname(current); if (parent === current) throw new Error("Pi Harness is not initialized here. Run the pi-harness initializer before opening Pi."); current = parent; } }
function inside(root: string, target: string) { const relative = path.relative(root, target); return relative === "" || (!relative.startsWith("..") && !path.isAbsolute(relative)); }
async function manifest(root: string): Promise<Manifest> { return YAML.parse(await readFile(path.join(root, "workspace.yaml"), "utf8")) ?? {}; }
function supervisorOutput() { try { const root = findRoot(process.cwd()); return (YAML.parse(readFileSync(path.join(root, "workspace.yaml"), "utf8")) as Manifest)?.subagents?.supervisor_output ?? "compact"; } catch { return "compact"; } }
async function settings(root: string) { const value = await manifest(root); return { docs: value.workspace?.docs_directory ?? "docs", projects: value.workspace?.projects_directory ?? "projects", worktrees: value.workspace?.worktrees_directory ?? "worktrees" }; }
function commandReferencesDocs(command: string, root: string, docs: string) { if (command.includes(path.resolve(root, docs))) return true; const escaped = docs.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); return new RegExp(`(^|[\\s"'=])${escaped}(?:/|(?=\\s|$))`).test(command); }
async function version() { return (JSON.parse(await readFile(path.join(PACKAGE_ROOT, "package.json"), "utf8")) as { version: string }).version; }
function externalDirectoryPolicy(settingsFile: string, packages: unknown[], fallback: "allow" | "ask" | "deny" = "ask") {
  const policy: Record<string, "allow" | "ask" | "deny"> = { "*": fallback, "/dev/null": "allow", "/tmp/*": "allow" };
  for (const source of packages) {
    if (typeof source !== "string" || (!source.startsWith(".") && !path.isAbsolute(source))) continue;
    policy[`${path.resolve(path.dirname(settingsFile), source)}/*`] = "allow";
  }
  return policy;
}
function bundledGraphCommand(graph: Manifest["code_graph"] = {}) {
  const legacyCorepack = graph.command === "corepack" && JSON.stringify(graph.args ?? []) === JSON.stringify(["pnpm", "exec", "codebase-memory-mcp"]);
  return legacyCorepack || !graph.command
    ? { command: process.execPath, args: [path.join(PACKAGE_ROOT, "node_modules", "codebase-memory-mcp", "bin.js")] }
    : { command: graph.command, args: graph.args ?? [] };
}

async function sync(root: string) {
  const config = await manifest(root); const packageVersion = await version();
  const managed = path.join(root, ".pi-harness"); await cp(path.join(PACKAGE_ROOT, "templates", "managed"), managed, { recursive: true, force: true });
  await writeFile(path.join(managed, "manifest.json"), JSON.stringify({ package: "pi-harness", version: packageVersion, generatedAt: new Date().toISOString() }, null, 2) + "\n");
  const settingFile = path.join(root, ".pi", "settings.json"); await mkdir(path.dirname(settingFile), { recursive: true });
  const current = existsSync(settingFile) ? JSON.parse(await readFile(settingFile, "utf8")) : {};
  const existingPackages = Array.isArray(current.packages) ? current.packages : [];
  const packages = [...existingPackages]; for (const source of [...REQUIRED_PI_PACKAGES, ...(config.pi?.packages ?? [])]) if (!packages.includes(source)) packages.push(source);
  const configured = config.agents ?? {}; const overrides = current.subagents?.agentOverrides ?? {};
  for (const [name, value] of Object.entries(configured)) if (name !== "orchestrator" && value.model) overrides[name] = { ...(overrides[name] ?? {}), model: value.model };
  await writeFile(settingFile, JSON.stringify({ ...current, ...(packages.length ? { packages } : {}), ...(configured.orchestrator?.model ? { defaultModel: configured.orchestrator.model } : {}), subagents: { ...(current.subagents ?? {}), agentOverrides: overrides } }, null, 2) + "\n");
  const subagents = config.subagents ?? {};
  const subagentConfigFile = path.join(root, ".pi", "extensions", "subagent", "config.json"); await mkdir(path.dirname(subagentConfigFile), { recursive: true });
  const currentSubagentConfig = existsSync(subagentConfigFile) ? JSON.parse(await readFile(subagentConfigFile, "utf8")) : {};
  await writeFile(subagentConfigFile, JSON.stringify({ ...currentSubagentConfig, asyncByDefault: subagents.async_by_default ?? true, toolDescriptionMode: subagents.tool_description_mode ?? "compact", completionBatch: { ...(currentSubagentConfig.completionBatch ?? {}), enabled: subagents.completion_batch ?? true }, control: { ...(currentSubagentConfig.control ?? {}), notifyOn: ["needs_attention"], notifyChannels: ["async"] }, intercomBridge: { ...(currentSubagentConfig.intercomBridge ?? {}), mode: subagents.intercom_bridge_mode ?? "always" } }, null, 2) + "\n");
  const graph = config.code_graph ?? {}; const mcpFile = path.join(root, ".mcp.json"); const mcp = existsSync(mcpFile) ? JSON.parse(await readFile(mcpFile, "utf8")) : {};
  const serverName = graph.server_name ?? "codebase-memory"; const graphProcess = bundledGraphCommand(graph);
  await writeFile(mcpFile, JSON.stringify({ ...mcp, mcpServers: { ...(mcp.mcpServers ?? {}), [serverName]: { ...graphProcess, lifecycle: graph.lifecycle ?? "lazy", idleTimeout: graph.idle_timeout ?? 10 } } }, null, 2) + "\n");
  const permission = JSON.parse(await readFile(path.join(PACKAGE_ROOT, "templates", "permission-config.json"), "utf8")); const p = config.permissions ?? {};
  permission.permission["*"] = p.default ?? "allow"; permission.permission.bash["*"] = p.shell ?? "allow"; permission.permission.mcp["*"] = p.mcp ?? "allow"; permission.permission.external_directory = externalDirectoryPolicy(settingFile, packages, p.external_directories ?? "ask");
  const permissionFile = path.join(root, ".pi", "extensions", "pi-permission-system", "config.json"); await mkdir(path.dirname(permissionFile), { recursive: true }); await writeFile(permissionFile, JSON.stringify(permission, null, 2) + "\n");
  return packageVersion;
}
function statePath(root: string, owner: string) { return path.join(root, FLOW_DIR, "state", `${encodeURIComponent(owner)}.json`); }
async function loadState(root: string, owner: string): Promise<WorkflowState | null> { try { return JSON.parse(await readFile(statePath(root, owner), "utf8")); } catch { return null; } }
async function saveState(root: string, state: WorkflowState) { const file = statePath(root, state.sessionId); await mkdir(path.dirname(file), { recursive: true }); await writeFile(file, JSON.stringify(state, null, 2) + "\n"); }
function render(state: WorkflowState) { return `Workflow ${state.id}: ${state.phase}\nProjects: ${state.projects.join(", ")}\nSession worktree: ${state.sessionWorktree ? state.sessionWorktree.branch : "none"}\nCI: ${state.checks.ciPassed ? "recorded" : "pending"}; code graph: ${state.checks.codeIndexed ? "recorded" : "pending"}`; }
function planPrompt(state: WorkflowState) { return `The workflow is in plan phase. Immediately load workspace-development-loop and workspace-knowledge-protocol; they are the workflow authority—never inspect node_modules, .pi internals, or package source to rediscover this workflow. Required order: (1) call workspace_knowledge orientation, then search/read relevant project architecture, contracts, decisions, and subject context; (2) inspect the available codebase-memory MCP tools and use the graph for structural discovery; (3) use targeted direct reads only for code facts not answered by knowledge or graph. After that evidence, verify that the provisional branch ${state.sessionWorktree?.branch ?? branchName(state.subject)} accurately names the outcome and record the coordination and affected-product branches. Do not replace unfamiliar structural exploration with broad parent file reading: launch the named explore agent via subagent (never generic delegate), async:true, clarify:false, context:fresh, artifacts:false, acceptance:{level:none,reason:"Pi Harness owns worker evidence, CI, and review."}, and with no cwd override, for every task that is not narrow and graph-known. Skip explore only when the graph and handoff already answer the narrow question. Parent may read non-doc workspace/project files but must never edit product files; docs are only through workspace_knowledge. Create durable Plan and Task entries with workspace_knowledge_record, and create/update a Reference titled Project architecture — <project> for every affected project: purpose, ownership, entry points, key modules, flows, interfaces, configuration, validation, and graph anchors. Record factual sections in natural names, never a hand-formatted Markdown body; matching headings update and new factual headings are added, preserving everything else.`; }

function parseWorkflowCommands(source: string) { const commands: string[] = []; const lines = source.split("\n"); for (let i = 0; i < lines.length; i++) { const match = lines[i]?.match(/^(\s*)run:\s*(\S.*?)\s*$/); if (!match) continue; if (!/^[|>]$/.test(match[2])) commands.push(match[2]); else { const indent = match[1].length; const body: string[] = []; for (i++; i < lines.length; i++) { const line = lines[i] ?? ""; if (line.trim() && line.match(/^\s*/)?.[0].length <= indent) { i--; break; } if (line.trim() && !line.trimStart().startsWith("#")) body.push(line.trim()); } if (body.length) commands.push(body.join(" && ")); } } return [...new Set(commands)]; }
async function readLocal(dir: string, file: string) { try { return await readFile(path.join(dir, file), "utf8"); } catch { return undefined; } }
async function localCi(dir: string, taskfile?: string, packageJson?: any) { const evidence: string[] = []; const commands: string[] = []; try { const files = await readdir(path.join(dir, ".github", "workflows")); for (const file of files.filter((x) => /(?:ci|check|test).*\.ya?ml$/i.test(x))) { commands.push(...parseWorkflowCommands(await readLocal(dir, path.join(".github", "workflows", file)) ?? "")); evidence.push(`Local CI workflow: .github/workflows/${file}`); } } catch { /* no local workflow */ }
  if (commands.length) return { commands: [...new Set(commands)], evidence, warnings: [] as string[] };
  if (taskfile?.match(/^\s{2,}ci:/m)) return { commands: ["task ci"], evidence: ["Taskfile ci task"], warnings: [] as string[] };
  const scripts = packageJson?.scripts ?? {}; const runner = String(packageJson?.packageManager ?? "").startsWith("pnpm@") ? "pnpm" : "npm run"; if (typeof scripts.ci === "string") return { commands: [`${runner} ci`], evidence: ["package.json ci script"], warnings: [] as string[] };
  const found = ["lint", "format:check", "typecheck", "build", "build-only", "test", "test:unit"].filter((name) => typeof scripts[name] === "string").map((name) => `${runner} ${name}`); return { commands: found, evidence: found.length ? ["package.json scripts: " + found.join(", ")] : [], warnings: [found.length ? "No explicit local CI workflow or ci script; confirm these commands." : "No local CI command was found; set ci explicitly."] };
}
function git(dir: string, args: string[]) { try { return execFileSync("git", ["-C", dir, ...args], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim() || undefined; } catch { return undefined; } }
function runGit(dir: string, args: string[]) { return execFileSync("git", ["-C", dir, ...args], { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim(); }
function worktreeDirectory(root: string, local: Awaited<ReturnType<typeof settings>>) {
  const directory = path.resolve(root, local.worktrees);
  if (!inside(root, directory) || directory === root) throw new Error("workspace.worktrees_directory must be a directory inside the workspace root.");
  return directory;
}
function startPoint(source: string, defaultBranch: string) { return git(source, ["rev-parse", "--verify", `${defaultBranch}^{commit}`]) ? defaultBranch : git(source, ["rev-parse", "--verify", `origin/${defaultBranch}^{commit}`]) ? `origin/${defaultBranch}` : undefined; }
type LifecycleEnvironment = { baseWorkspace: string; baseProject?: string };
function lifecycleEnvironment(context: LifecycleEnvironment) { const env: NodeJS.ProcessEnv = { ...process.env }; delete env.PI_SUBAGENT_CHILD; delete env.PI_SUBAGENT_CHILD_AGENT; delete env.PI_SUBAGENT_PARENT_SESSION; return { ...env, PH_WORKSPACE_BASE: context.baseWorkspace, ...(context.baseProject ? { PH_PROJECT_BASE: context.baseProject } : {}) }; }
function runLifecycle(directory: string, commands: string[] | undefined, label: string, context: LifecycleEnvironment) { for (const command of commands ?? []) { if (typeof command !== "string" || !command.trim()) throw new Error(`${label} commands must be non-empty strings.`); try { execFileSync("/bin/sh", ["-lc", command], { cwd: directory, env: lifecycleEnvironment(context), stdio: "inherit" }); } catch { throw new Error(`${label} failed: ${command}`); } } }
function hasWorkspaceChanges(root: string, worktrees: string) { const ignored = `${worktrees.replace(/\\/g, "/").replace(/\/$/, "")}/`; return (git(root, ["status", "--porcelain"]) ?? "").split("\n").some((line) => { const file = line.slice(3).replace(/\\/g, "/"); return file && !file.startsWith(ignored); }); }
function sessionTarget(directory: string, session: string) { const name = path.basename(session); if (!/^[a-z0-9][a-z0-9-]{0,63}$/.test(name)) throw new Error("Session must be a worktree path returned by workspace_session list."); const target = path.resolve(directory, name); if (!inside(directory, target)) throw new Error("Session path escapes workspace.worktrees_directory."); return target; }
async function createSessionWorktree(root: string, owner: string, subject: string) {
  if (!subject.trim()) throw new Error("A workflow subject is required.");
  if (!git(root, ["rev-parse", "--is-inside-work-tree"])) throw new Error("The coordination workspace must be an initialized Git repository before creating a session worktree.");
  const local = await settings(root); const configured = (await manifest(root)).projects ?? []; const directory = worktreeDirectory(root, local);
  if (hasWorkspaceChanges(root, local.worktrees)) throw new Error("Commit or stash coordination-workspace changes before creating a session worktree.");
  const branch = branchName(subject); const key = `${slugify(subject).slice(0, 48)}-${createHash("sha256").update(owner).digest("hex").slice(0, 8)}`; const target = path.join(directory, key);
  if (existsSync(target)) throw new Error(`Session worktree already exists at ${path.relative(root, target)}.`);
  if (git(root, ["rev-parse", "--verify", `refs/heads/${branch}`])) throw new Error(`The coordination branch ${branch} already exists. Start or reattach that workflow instead of creating another session worktree.`);
  const sourceProjects = path.resolve(root, local.projects); const targetProjects = path.resolve(target, local.projects);
  if (!inside(root, directory) || !inside(root, sourceProjects) || !inside(target, targetProjects)) throw new Error("workspace projects and worktrees directories must remain inside their workspace roots.");
  const planned = configured.map((project) => { const source = path.resolve(sourceProjects, project.path); const destination = path.resolve(targetProjects, project.path); if (!inside(sourceProjects, source) || !inside(targetProjects, destination)) throw new Error(`Project path escapes projects/: ${project.name}.`); if (!git(source, ["rev-parse", "--is-inside-work-tree"])) throw new Error(`${project.name} is not an initialized Git checkout at ${path.relative(root, source)}.`); if (git(source, ["status", "--porcelain"])) throw new Error(`Commit or stash changes in ${project.name} before creating a session worktree.`); if (git(source, ["rev-parse", "--verify", `refs/heads/${branch}`])) throw new Error(`${project.name} already has branch ${branch}; create or reattach its matching session instead.`); const start = startPoint(source, project.default_branch ?? "main"); if (!start) throw new Error(`${project.name} has no local or origin ${project.default_branch ?? "main"} branch to start from.`); return { project, source, destination, start }; });
  await mkdir(path.dirname(target), { recursive: true }); runGit(root, ["worktree", "add", "-b", branch, target, "HEAD"]);
  try {
    const sourceSettings = path.join(root, ".pi", "settings.json"); const targetSettings = path.join(target, ".pi", "settings.json"); if (existsSync(sourceSettings)) { await mkdir(path.dirname(targetSettings), { recursive: true }); await cp(sourceSettings, targetSettings, { force: true }); }
    await sync(target); runLifecycle(target, (await manifest(target)).workspace?.setup, "workspace setup", { baseWorkspace: root });
    for (const item of planned) { await mkdir(path.dirname(item.destination), { recursive: true }); runGit(item.source, ["worktree", "add", "-b", branch, item.destination, item.start]); runLifecycle(item.destination, item.project.setup, `${item.project.name} setup`, { baseWorkspace: root, baseProject: item.source }); }
  } catch (error) { throw new Error(`Session worktree was created at ${path.relative(root, target)}, but setup did not complete: ${error instanceof Error ? error.message : String(error)}`); }
  const state = createWorkflow(subject, owner); const products = Object.fromEntries(planned.map((item) => [item.project.name, path.relative(target, item.destination)])); const next = { ...state, projects: ["workspace", ...planned.map((item) => item.project.name)], branches: { workspace: branch, ...Object.fromEntries(planned.map((item) => [item.project.name, branch])) }, sessionWorktree: { branch, products } }; await saveState(target, next);
  return { branch, key, target, state: next };
}
async function cleanupSessionWorktree(root: string, session: string) {
  const local = await settings(root); const directory = worktreeDirectory(root, local); const target = sessionTarget(directory, session); const config = await manifest(root); const configured = config.projects ?? [];
  if (!existsSync(target) || !git(target, ["rev-parse", "--is-inside-work-tree"])) throw new Error(`No session worktree exists at ${path.relative(root, target)}.`);
  const sourceProjects = path.resolve(root, local.projects); const targetProjects = path.resolve(target, local.projects); const planned = configured.map((project) => { const source = path.resolve(sourceProjects, project.path); const destination = path.resolve(targetProjects, project.path); if (!inside(sourceProjects, source) || !inside(targetProjects, destination) || !git(source, ["rev-parse", "--is-inside-work-tree"]) || !git(destination, ["rev-parse", "--is-inside-work-tree"])) throw new Error(`Session project worktree is invalid for ${project.name}.`); return { project, source, destination }; });
  for (const item of planned) runLifecycle(item.destination, item.project.cleanup, `${item.project.name} cleanup`, { baseWorkspace: root, baseProject: item.source });
  runLifecycle(target, config.workspace?.cleanup, "workspace cleanup", { baseWorkspace: root });
  for (const item of planned) if (git(item.destination, ["status", "--porcelain"])) throw new Error(`${item.project.name} has uncommitted changes after cleanup; refusing to remove its worktree.`);
  if (git(target, ["status", "--porcelain"])) throw new Error("The session workspace has uncommitted changes after cleanup; refusing to remove it.");
  for (const item of planned) { runGit(item.source, ["worktree", "remove", item.destination]); runGit(item.source, ["worktree", "prune"]); }
  runGit(root, ["worktree", "remove", target]); runGit(root, ["worktree", "prune"]);
  return { target };
}
type SavedWorkflow = { root: string; state: WorkflowState };
function primaryWorkspaceRoot(root: string) { const common = git(root, ["rev-parse", "--path-format=absolute", "--git-common-dir"]); if (!common) return root; const candidate = path.dirname(path.resolve(root, common)); return existsSync(path.join(candidate, "workspace.yaml")) ? candidate : root; }
async function workflowStates(root: string): Promise<SavedWorkflow[]> { const directory = path.join(root, FLOW_DIR, "state"); return Promise.all((await readdir(directory).catch(() => [])).filter((file) => file.endsWith(".json")).map(async (file) => ({ root, state: JSON.parse(await readFile(path.join(directory, file), "utf8")) as WorkflowState }))); }
async function savedWorkflows(root: string) { const primary = primaryWorkspaceRoot(root); const local = await settings(primary); const directory = worktreeDirectory(primary, local); const candidates = [primary, ...(await readdir(directory, { withFileTypes: true }).catch(() => [])).filter((entry) => entry.isDirectory()).map((entry) => path.join(directory, entry.name)).filter((entry) => existsSync(path.join(entry, "workspace.yaml")))]; const unique = [...new Set([root, ...candidates].map((entry) => path.resolve(entry)))]; const latest = new Map<string, SavedWorkflow>(); for (const saved of (await Promise.all(unique.map(workflowStates))).flat()) { const key = `${saved.root}\0${saved.state.id}`; const prior = latest.get(key); if (!prior || saved.state.updatedAt > prior.state.updatedAt) latest.set(key, saved); } return [...latest.values()]; }
async function findSavedWorkflow(root: string, query: string) { const value = query.trim(); if (!value) throw new Error("A workflow id is required."); const states = await savedWorkflows(root); const exact = states.filter(({ state }) => state.id === value || state.sessionId === value); const matches = exact.length ? exact : states.filter(({ state }) => state.id.startsWith(value) || state.sessionId.startsWith(value)); if (!matches.length) throw new Error("No matching workflow."); if (matches.length > 1) throw new Error("Workflow id is ambiguous; provide a longer id."); return matches[0]!; }
async function bindWorkflowState(root: string, state: WorkflowState, owner: string) { const next = { ...state, sessionId: owner, updatedAt: new Date().toISOString() }; await saveState(root, next); if (state.sessionId !== owner) await rename(statePath(root, state.sessionId), `${statePath(root, state.sessionId)}.rebound`).catch(() => undefined); return next; }
async function forkConversation(sourceFile: string, target: string) { const source = await readFile(sourceFile, "utf8").catch(() => ""); if (source.trim()) return SessionManager.forkFrom(sourceFile, target); const fresh = SessionManager.create(target); const file = fresh.getSessionFile(); if (!file) throw new Error("Could not allocate a persisted target session."); await mkdir(path.dirname(file), { recursive: true }); await writeFile(file, `${JSON.stringify(fresh.getHeader())}\n`, { flag: "wx" }); return fresh; }
function githubRepository(remote?: string) { const match = remote?.match(/github\.com[/:]([^/]+\/[^/#]+?)(?:\.git)?$/i); return match?.[1]; }
function pullRequestAvailable(project?: NonNullable<Manifest["projects"]>[number]) { const repository = githubRepository(project?.repository); if (!repository) return false; try { return execFileSync("gh", ["api", `repos/${repository}`, "--jq", ".permissions.push"], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"], timeout: 5000 }).trim() === "true"; } catch { return false; } }
function workspacePullRequestAvailable(root: string) { return pullRequestAvailable({ name: "workspace", path: ".", repository: git(root, ["remote", "get-url", "origin"]), ci: [] }); }
async function discover(root: string) { const config = await manifest(root); const projectsDirectory = config.workspace?.projects_directory ?? "projects"; const projectsRoot = path.resolve(root, projectsDirectory); const entries = await readdir(projectsRoot, { withFileTypes: true }).catch(() => []); const folders = entries.filter((entry) => entry.isDirectory() && !entry.name.startsWith(".")).map((entry) => entry.name); if (!folders.length) throw new Error(`No local projects were found in ${projectsDirectory}/. Clone or initialize repositories there, then run onboarding again.`);
  const discovered = await Promise.all(folders.map(async (name) => { const dir = path.join(projectsRoot, name); if (!(await readdir(dir).catch(() => [])).length) return null; const packageText = await readLocal(dir, "package.json"); let pkg: any = {}; try { pkg = packageText ? JSON.parse(packageText) : {}; } catch { /* surfaced as warning below */ } const taskfile = await readLocal(dir, "Taskfile.yml") ?? await readLocal(dir, "Taskfile.yaml"); const ci = await localCi(dir, taskfile, pkg); const repository = git(dir, ["remote", "get-url", "origin"]); const branch = git(dir, ["branch", "--show-current"]) ?? git(dir, ["symbolic-ref", "--short", "HEAD"]) ?? "main"; const warnings = [...ci.warnings]; if (!existsSync(path.join(dir, ".git"))) warnings.push("Directory is not a Git repository; initialize it before implementation."); if (!repository) warnings.push("No origin remote was found; this is a local-only project."); return { name, ...(repository ? { repository } : {}), path: name, default_branch: branch, ci: ci.commands, evidence: [`Local directory: ${dir}`, ...(repository ? [`Origin remote: ${repository}`] : []), ...ci.evidence], warnings }; }));
  const projects = discovered.filter((project): project is NonNullable<typeof project> => project !== null); if (!projects.length) throw new Error(`No initialized or non-empty local projects were found in ${projectsDirectory}/.`); return projects;
}
function models() { try { return execFileSync("pi", ["--list-models"], { encoding: "utf8" }).split("\n").slice(1).map((line) => line.trim().split(/\s+/)).filter((part) => part.length >= 2).map((part) => `${part[0]}/${part[1]}`); } catch { return []; } }
function modelProposal(list: string[]) { const pick = (terms: string[], fallback?: string) => list.find((item) => terms.some((term) => item.toLowerCase().includes(term))) ?? fallback ?? list[0]; const main = pick(["/main", "/max", "/auto"]); return { orchestrator: { model: main }, impl: { model: pick(["/code", "coder"], main) }, "impl-lite": { model: pick(["code-lite", "fast", "lite"], main) }, explore: { model: pick(["/main", "/chat", "/auto"], main) } }; }
function onboardingManifest(current: string, projects: any[], available: string[]) { const value: any = YAML.parse(current) ?? {}; value.version ??= 1; value.workspace ??= { docs_directory: "docs", projects_directory: "projects" }; value.workspace.worktrees_directory ??= "worktrees"; value.workspace.setup ??= []; value.workspace.cleanup ??= []; const existing = new Map((Array.isArray(value.projects) ? value.projects : []).map((project: any) => [project.name, project])); value.agents = modelProposal(available); value.projects = projects.map((project) => { const prior = existing.get(project.name) ?? {}; return { name: project.name, ...(project.repository ? { repository: project.repository } : {}), path: project.path, default_branch: project.default_branch, depends_on: prior.depends_on ?? [], ci: project.ci, setup: prior.setup ?? [], cleanup: prior.cleanup ?? [] }; }); return YAML.stringify(value); }
function validateLifecycle(value: unknown, label: string) { if (value !== undefined && (!Array.isArray(value) || !value.every((command) => typeof command === "string" && command.trim()))) throw new Error(`${label} must be an array of non-empty shell commands.`); }
function validateManifest(text: string) { const value = YAML.parse(text) as Manifest; if (!value || !Array.isArray(value.projects)) throw new Error("The proposal must be a complete workspace.yaml with a projects array."); validateLifecycle(value.workspace?.setup, "workspace.setup"); validateLifecycle(value.workspace?.cleanup, "workspace.cleanup"); for (const project of value.projects) { if (!project?.name || !project.path || !Array.isArray(project.ci) || !project.ci.every((command) => typeof command === "string" && command.trim()) || (project.repository !== undefined && typeof project.repository !== "string")) throw new Error("Every project requires name, path, and a ci array of non-empty command strings; repository is optional."); validateLifecycle(project.setup, `${project.name}.setup`); validateLifecycle(project.cleanup, `${project.name}.cleanup`); } }
function proposalToken(text: string) { return createHash("sha256").update(text).digest("hex").slice(0, 24); }
async function stageProposal(root: string, text: string) { validateManifest(text); const file = path.join(root, ONBOARDING_FILE); await mkdir(path.dirname(file), { recursive: true }); await writeFile(file, JSON.stringify({ baseManifest: await readFile(path.join(root, "workspace.yaml"), "utf8"), manifest: text }, null, 2) + "\n"); }
async function applyProposal(root: string) { const file = path.join(root, ONBOARDING_FILE); const proposal = JSON.parse(await readFile(file, "utf8")); if (await readFile(path.join(root, "workspace.yaml"), "utf8") !== proposal.baseManifest) throw new Error("workspace.yaml changed after the proposal was staged. Re-run onboarding."); validateManifest(proposal.manifest); await writeFile(path.join(root, "workspace.yaml"), proposal.manifest); await sync(root); await unlink(file); }

function normal(text: string) { return text.replace(/\s+/g, " ").trim(); }
async function entries(dir: string) { const files = await readdir(dir, { withFileTypes: true }).catch(() => []); const all = await Promise.all(files.map(async (file) => { const target = path.join(dir, file.name); return file.isDirectory() ? entries(target) : file.isFile() && file.name.endsWith(".md") ? [target] : []; })); return all.flat(); }
function knowledgePath(root: string, docs: string, entryPath: string) { const target = path.resolve(root, entryPath); const base = path.resolve(root, docs); if (!inside(base, target)) throw new Error("Knowledge entry path escapes docs/."); return target; }
function validateKnowledge(kind: string, title: string, body: string) { if (!KINDS[kind]) throw new Error("Unknown knowledge kind."); if (!title.trim() || !body.includes(`# ${title.trim()}`)) throw new Error("Knowledge must contain an H1 matching title."); for (const heading of KINDS[kind]) if (!body.includes(`## ${heading}`)) throw new Error(`Knowledge is missing required section: ${heading}`); }
function sectionPatch(body: string, section: string, expected: string, next: string) { const heading = new RegExp(`^## ${section.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\r?\\n`, "m"); const match = heading.exec(body); if (!match || match.index === undefined) throw new Error(`Section not found: ${section}`); const start = match.index + match[0].length; const following = /^## .+$/gm; following.lastIndex = start; const nextHeading = following.exec(body); const end = nextHeading?.index ?? body.length; const current = body.slice(start, end); if (current.trim() !== expected.trim()) throw new Error(`Section changed since it was read: ${section}.`); if (normal(current) === normal(next)) return { body, changed: false }; return { body: `${body.slice(0, start)}${next.trim()}\n\n${body.slice(end)}`, changed: true }; }
function normalizedSection(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, "").trim(); }
function cleanSection(value: string) { const section = value.replace(/[\r\n#]+/g, " ").trim(); if (!section) throw new Error("Knowledge section names cannot be empty."); return section; }
function canonicalKind(kind: string) { const cleaned = cleanSection(kind); return Object.keys(KINDS).find((candidate) => normalizedSection(candidate) === normalizedSection(cleaned)) ?? cleaned; }
function kindDirectory(kind: string) { return canonicalKind(kind).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "reference"; }
function canonicalSection(kind: string, section: string) { const cleaned = cleanSection(section); return KINDS[canonicalKind(kind)]?.find((candidate) => normalizedSection(candidate) === normalizedSection(cleaned)) ?? cleaned; }
function emptyKnowledgeEntry(kind: string, title: string, sections: Record<string, string>) { const canonical = canonicalKind(kind); const supplied = Object.entries(sections).map(([section, content]) => [canonicalSection(canonical, section), content] as const); const required = KINDS[canonical]; if (!required) return `# ${title.trim()}\n\n${supplied.map(([section, content]) => `## ${section}\n\n${content.trim()}`).join("\n\n")}\n`; const known = new Map(supplied.filter(([section]) => required.includes(section))); const extra = supplied.filter(([section]) => !required.includes(section)); const body = `# ${title.trim()}\n\n${required.map((section) => `## ${section}\n\n${known.get(section)?.trim() ?? ""}`).join("\n\n")}${extra.length ? `\n\n${extra.map(([section, content]) => `## ${section}\n\n${content.trim()}`).join("\n\n")}` : ""}\n`; validateKnowledge(canonical, title, body); return body; }
function replaceKnowledgeSection(body: string, section: string, next: string) { const requested = cleanSection(section); const headings = [...body.matchAll(/^## (.+)$/gm)]; const found = headings.find((heading) => normalizedSection(heading[1]!) === normalizedSection(requested)); if (!found || found.index === undefined) { if (!next.trim()) return { body, changed: false }; return { body: `${body.trimEnd()}\n\n## ${requested}\n\n${next.trim()}\n`, changed: true }; } const start = found.index + found[0].length + 1; const nextHeading = headings.find((heading) => (heading.index ?? 0) > found.index!); const end = nextHeading?.index ?? body.length; const current = body.slice(start, end); if (normal(current) === normal(next)) return { body, changed: false }; return { body: `${body.slice(0, start)}\n${next.trim()}\n\n${body.slice(end)}`, changed: true }; }

export default function workspaceFlow(pi: ExtensionAPI) {
  const rootFor = (ctx: ExtensionContext) => findRoot(ctx.cwd); const approvals = new Set<string>();
  pi.registerMessageRenderer?.("subagent_supervisor_request", (message: any, { expanded }: { expanded: boolean }, theme: any) => { if (supervisorOutput() === "full") return new Text(String(message.content)); const details = message.details as { reason?: string; agent?: string; runId?: string; childIndex?: number } | undefined; const body = String(message.content).split(/\n\s*\n/).slice(-1)[0]?.trim() || "No details supplied."; const label = details?.reason === "need_decision" ? "needs a decision" : details?.reason === "interview_request" ? "requests input" : "update"; const title = `${details?.agent ?? "subagent"} ${label}: ${body}`; const meta = `run ${details?.runId ?? "unknown"}, child ${details?.childIndex ?? "?"}`; return new Text(expanded ? `${title}\n${theme.fg("dim", meta)}` : title); });
  pi.events?.on?.("ask:answered", (raw) => { const value = raw as any; const token = value.context?.match(/pi-harness:onboarding-apply:([a-f0-9]{24})/)?.[1]; if (token && value.response?.kind === "selection" && value.response.selections?.includes("Apply now")) approvals.add(token); });
  const send = (text: string) => pi.sendUserMessage(text, { deliverAs: "followUp" });
  pi.registerCommand("workspace:sync", { description: "Synchronize generated settings from workspace.yaml", handler: async (_args, ctx) => { const v = await sync(rootFor(ctx)); ctx.ui.notify(`Synced pi-harness ${v}.`, "info"); } });
  pi.registerCommand("workspace:onboard", { description: "Analyze local projects and guide workspace configuration", handler: async (args, ctx) => { if (isSubagent()) throw new Error("Only the orchestrator may onboard."); if (args.trim()) throw new Error("Onboarding takes no sources. Set up repositories under projects/ first."); await send("Start local-first workspace onboarding. Load workspace-onboarding and ask-user skills. Call workspace_onboarding action=discover with no source arguments. Analyze only local projects/*; never call GitHub, web, gh, or remote inspection. Use ask_user to confirm CI for each included project, dependency relationships, model pins, and the setup/cleanup commands for workspace sessions; do not infer those preferences. Ask one focused decision at a time. Present the complete workspace.yaml, including workspace.setup, workspace.cleanup, and each project setup/cleanup array, immediately stage that exact proposal with workspace_onboarding action=propose, then ask the single final token-bound Apply now / Revise proposal / Cancel question. Never ask any earlier approval question, and never create or clone repositories during onboarding."); } });
  pi.registerCommand("workspace:cleanup", { description: "Clean up a completed isolated workflow", handler: async (id, ctx) => { if (isSubagent()) throw new Error("Only the orchestrator may clean up a workflow."); const root = rootFor(ctx); const primary = primaryWorkspaceRoot(root); if (primary !== root) throw new Error("Run /workspace:cleanup from the primary coordination checkout, not from an active session worktree."); const saved = await findSavedWorkflow(root, id); if (saved.root === primary) throw new Error("The matching workflow is not stored in an isolated worktree."); const removed = await cleanupSessionWorktree(primary, path.relative(path.resolve(primary, (await settings(primary)).worktrees), saved.root)); await send(`Cleaned up workflow worktree ${path.relative(primary, removed.target)}.`); } });
  pi.registerCommand("workspace:plan", { description: "Create an isolated workflow and start user-controlled planning", handler: async (subject, ctx) => { if (isSubagent()) throw new Error("Only the orchestrator may start a workflow."); const root = rootFor(ctx); const owner = sessionId(ctx); if (await loadState(root, owner)) throw new Error("This session already owns a workflow."); const state = createWorkflow(subject, owner); if (!git(root, ["rev-parse", "--is-inside-work-tree"])) { await saveState(root, state); pi.setSessionName(state.subject); ctx.ui.notify("Coordination root is not a Git checkout; planning in place without concurrent isolation.", "warning"); await send(planPrompt(state)); return; } const primary = primaryWorkspaceRoot(root); if (primary !== root) throw new Error("This is already a session worktree. Use /workspace:continue to rebind its saved workflow."); const sourceFile = ctx.sessionManager.getSessionFile(); if (!sourceFile) throw new Error("The Pi session must be persisted before /workspace:plan can move it into an isolated worktree."); await ctx.waitForIdle(); pi.setSessionName(state.subject); const created = await createSessionWorktree(root, owner, subject); let forked: SessionManager; try { forked = await forkConversation(sourceFile, created.target); } catch (error) { throw new Error(`Created ${path.relative(root, created.target)}, but could not fork the Pi session. Recover with /workspace:continue ${created.state.id}. ${error instanceof Error ? error.message : String(error)}`); } const sessionFile = forked.getSessionFile(); if (!sessionFile) throw new Error(`Created ${path.relative(root, created.target)}, but the replacement Pi session was not persisted. Recover with /workspace:continue ${created.state.id}.`); const next = { ...created.state, sessionId: forked.getSessionId(), updatedAt: new Date().toISOString() }; await saveState(created.target, next); let result: { cancelled: boolean }; try { result = await ctx.switchSession(sessionFile, { withSession: async (nextCtx) => { nextCtx.ui.notify(`Planning in isolated worktree: ${created.target}`, "info"); await nextCtx.sendUserMessage(planPrompt(next)); } }); } catch (error) { throw new Error(`Created ${path.relative(root, created.target)}, but Pi could not switch sessions. Recover with /workspace:continue ${next.id}. ${error instanceof Error ? error.message : String(error)}`); } if (result.cancelled) throw new Error(`Session switch was cancelled. The isolated workflow is preserved; recover with /workspace:continue ${next.id}.`); if (next.sessionId !== owner) await rename(statePath(created.target, owner), `${statePath(created.target, owner)}.rebound`).catch(() => undefined); } });
  pi.registerCommand("workspace:code", { description: "User-authorize plan/review to code", handler: async (feedback, ctx) => { const root = rootFor(ctx); const state = await loadState(root, sessionId(ctx)); if (!state) throw new Error("No active workflow."); await saveState(root, transition(state, "code")); await send(`The workflow is now in code. Delegate every product edit with the pi-subagents subagent tool. Route a one-file documentation, test, config, or localized implementation change to impl-lite; use impl only for multi-file, cross-project, contract, or genuinely complex work. Never use generic delegate, an intercom-only child, or foreground parallel execution. Launch async:true, clarify:false, context:fresh, artifacts:false, acceptance:{level:none,reason:"Pi Harness owns worker evidence, CI, and review."}, and NO cwd override so child Pi loads this session workspace's tools. State the target checkout path in the handoff and have the worker operate beneath projects/. Include acceptance criteria, graph evidence, and configured CI, but never tell workers to read canonical docs or call workspace knowledge. One writer per checkout at a time; each workspace session owns a separate product checkout. Continue independent orchestration work; when waiting is necessary, use wait rather than status-polling. The resolved workspace.yaml model pins for impl and impl-lite apply to those exact agent names. ${feedback.trim() ? `Address: ${feedback.trim()}` : "Implement the approved plan."} Before review, record material architecture/contract/decision outcomes, commit tracked coordination changes on the workspace branch, and create/record a workspace PR if its GitHub origin has usable gh access. Collect concise structured handoffs, run configured CI, update canonical knowledge, push branches and create PRs only where available, then record evidence and enter review.`); } });
  pi.registerCommand("workspace:done", { description: "User-authorize review closure", handler: async (_args, ctx) => { const root = rootFor(ctx); const state = await loadState(root, sessionId(ctx)); if (!state) throw new Error("No active workflow."); await saveState(root, transition(state, "done")); await send("The workflow is done. Do not edit, merge, create PRs, or write knowledge. Summarize PRs in dependency order and offer cleanup only after confirmed merges."); } });
  pi.registerCommand("workspace:status", { description: "Show workflow state", handler: async (_args, ctx) => ctx.ui.notify((await loadState(rootFor(ctx), sessionId(ctx))) ? render((await loadState(rootFor(ctx), sessionId(ctx)))!) : "No active workflow.", "info") });
  pi.registerCommand("workspace:continue", { description: "Resume or rebind a saved isolated workflow", handler: async (id, ctx) => { if (isSubagent()) throw new Error("Only the orchestrator may continue a workflow."); const root = rootFor(ctx); const saved = await findSavedWorkflow(root, id); const owner = sessionId(ctx); if (path.resolve(saved.root) === path.resolve(root)) { const next = await bindWorkflowState(root, saved.state, owner); pi.setSessionName(next.subject); await send(`Resume workflow ${next.id} in ${next.phase} phase. Call workspace_workflow status, load workspace-development-loop and workspace-knowledge-protocol, and continue from the saved evidence without repeating completed work.`); return; } await ctx.waitForIdle(); const sessions = await SessionManager.list(saved.root).catch(() => []); let target = sessions.find((session) => session.id === saved.state.sessionId)?.path; let next = saved.state; if (!target) { const sourceFile = ctx.sessionManager.getSessionFile(); if (!sourceFile) throw new Error("No saved Pi conversation was found for this workflow, and the current session is not persisted for a recovery fork."); const forked = await forkConversation(sourceFile, saved.root); target = forked.getSessionFile(); if (!target) throw new Error("Could not persist a replacement Pi session in the workflow worktree."); next = await bindWorkflowState(saved.root, saved.state, forked.getSessionId()); } const result = await ctx.switchSession(target, { withSession: async (nextCtx) => { nextCtx.ui.notify(`Resumed isolated workflow: ${next.id}`, "info"); await nextCtx.sendUserMessage(`Resume workflow ${next.id} in ${next.phase} phase. Call workspace_workflow status, load workspace-development-loop and workspace-knowledge-protocol, and continue from the saved evidence without repeating completed work.`); } }); if (result.cancelled) throw new Error("Session switch was cancelled; the saved workflow was left intact."); } });

  pi.registerTool({ name: "workspace_session", label: "Workspace Session", description: "List or safely clean up isolated workflow worktrees. Creation is owned exclusively by /workspace:plan.", parameters: Type.Object({ action: Type.Union([Type.Literal("list"), Type.Literal("cleanup")]), session: Type.Optional(Type.String()) }), async execute(_id, input, _signal, _update, ctx) { if (isSubagent()) throw new Error("Only the orchestrator manages workspace sessions."); const root = rootFor(ctx); const primary = primaryWorkspaceRoot(root); const local = await settings(primary); const directory = worktreeDirectory(primary, local); if (input.action === "list") { const output = git(primary, ["worktree", "list", "--porcelain"]) ?? ""; const sessions = output.split("\n\n").map((entry) => entry.match(/^worktree (.+)$/m)?.[1]).filter((entry): entry is string => Boolean(entry && inside(directory, entry))).map((entry) => path.relative(primary, entry)); return { content: [{ type: "text", text: JSON.stringify({ directory: path.relative(primary, directory), sessions }, null, 2) }], details: { directory: path.relative(primary, directory), sessions } }; } if (primary !== root) throw new Error("Cleanup must run from the primary coordination checkout, not an active session worktree."); if (!input.session) throw new Error("cleanup requires a session name from workspace_session list."); const removed = await cleanupSessionWorktree(primary, input.session); return { content: [{ type: "text", text: `Cleaned up session worktree ${path.relative(primary, removed.target)}.` }], details: { path: path.relative(primary, removed.target), removed: true } }; } });
  pi.registerTool({ name: "workspace_workflow", label: "Workspace Workflow", description: "Read or record workflow state; review requires a committed coordination workspace, CI, graph evidence, and PRs wherever GitHub access is available.", parameters: Type.Object({ action: Type.Union([Type.Literal("status"), Type.Literal("update"), Type.Literal("record_checks"), Type.Literal("enter_review")]), projects: Type.Optional(Type.Array(Type.String())), branches: Type.Optional(Type.Record(Type.String(), Type.String())), pullRequests: Type.Optional(Type.Record(Type.String(), Type.Number())), notes: Type.Optional(Type.Array(Type.String())), ciPassed: Type.Optional(Type.Boolean()), codeIndexed: Type.Optional(Type.Boolean()) }), async execute(_id, input, _signal, _update, ctx) { const root = rootFor(ctx); const state = await loadState(root, sessionId(ctx)); if (!state) throw new Error("No active workflow."); if (input.action === "status") return { content: [{ type: "text", text: render(state) }], details: state }; if (isSubagent()) throw new Error("Only the orchestrator updates workflow state."); if (input.action === "enter_review") { if (!state.checks.ciPassed || !state.checks.codeIndexed) throw new Error("CI and code-index checks must be recorded before review."); const workspaceBranch = git(root, ["branch", "--show-current"]); if (workspaceBranch === "main") throw new Error("Commit coordination changes on their workflow branch, not main, before review."); const pendingWorkspaceChanges = git(root, ["status", "--porcelain"]); if (pendingWorkspaceChanges) throw new Error("Commit all non-ignored coordination-workspace changes before review."); const configured = (await manifest(root)).projects ?? []; const required = state.projects.filter((name) => name !== "workspace" && pullRequestAvailable(configured.find((project) => project.name === name))); if (workspacePullRequestAvailable(root)) required.unshift("workspace"); const missing = required.filter((name) => !state.pullRequests[name]); if (missing.length) throw new Error(`Open and record PRs before review. GitHub PR access is available for: ${missing.join(", ")}`); const next = transition(state, "review"); await saveState(root, next); return { content: [{ type: "text", text: render(next) }], details: { ...next, pullRequestsRequired: required } }; } if (!["plan", "code"].includes(state.phase)) throw new Error(`Cannot record workflow evidence in ${state.phase}.`); const next = { ...state, projects: input.projects ? [...new Set(["workspace", ...input.projects])] : state.projects, branches: input.branches ?? state.branches, pullRequests: input.pullRequests ?? state.pullRequests, notes: input.notes ?? state.notes, checks: { ciPassed: input.ciPassed ?? state.checks.ciPassed, codeIndexed: input.codeIndexed ?? state.checks.codeIndexed }, updatedAt: new Date().toISOString() }; await saveState(root, next); return { content: [{ type: "text", text: render(next) }], details: next }; } });
  pi.registerTool({ name: "workspace_onboarding", label: "Workspace Onboarding", description: "Analyze local projects and stage/apply a reviewed workspace manifest.", parameters: Type.Object({ action: Type.Union([Type.Literal("discover"), Type.Literal("propose"), Type.Literal("apply")]), manifest: Type.Optional(Type.String()), approvalToken: Type.Optional(Type.String()) }), async execute(_id, input, _signal, _update, ctx) { if (isSubagent()) throw new Error("Only the orchestrator may onboard."); const root = rootFor(ctx); if (input.action === "discover") { const projects = await discover(root); const available = models(); const text = onboardingManifest(await readFile(path.join(root, "workspace.yaml"), "utf8"), projects, available); return { content: [{ type: "text", text: JSON.stringify({ proposed_workspace_yaml: text, projects, available_models: available, suggested_agents: modelProposal(available) }, null, 2) }], details: { manifest: text, repositories: projects, models: available } }; } if (input.action === "propose") { if (!input.manifest?.trim()) throw new Error("propose requires complete workspace.yaml."); await stageProposal(root, input.manifest); const token = proposalToken(input.manifest); return { content: [{ type: "text", text: `Staged proposal. Ask ask_user Apply now / Revise proposal / Cancel using context pi-harness:onboarding-apply:${token}; only then call apply with approvalToken.` }], details: { approvalToken: token } }; } const proposal = JSON.parse(await readFile(path.join(root, ONBOARDING_FILE), "utf8")); const token = proposalToken(proposal.manifest); if (!input.approvalToken || input.approvalToken !== token || !approvals.delete(token)) throw new Error("Applying onboarding requires a fresh ask_user response selecting Apply now for this exact proposal."); await applyProposal(root); return { content: [{ type: "text", text: "Applied workspace onboarding proposal and synchronized generated configuration." }], details: { applied: true } }; } });
  pi.registerTool({ name: "workspace_knowledge", label: "Workspace Knowledge", description: "Orient to, search, and read canonical workspace knowledge. Begin planning with orientation; use workspace_knowledge_record for every normal write.", parameters: Type.Object({ action: Type.Union([Type.Literal("orientation"), Type.Literal("search"), Type.Literal("read")]), query: Type.Optional(Type.String()), entryPath: Type.Optional(Type.String()), projects: Type.Optional(Type.Array(Type.String())) }), async execute(_id, input, _signal, _update, ctx) { if (isSubagent()) throw new Error("Only the orchestrator may access canonical knowledge."); const root = rootFor(ctx); const local = await settings(root); const docsRoot = path.resolve(root, local.docs); const files = await entries(docsRoot); if (input.action === "orientation") { const names = (input.projects ?? []).map((project) => project.toLowerCase()); const results = await Promise.all(files.map(async (file) => ({ path: path.relative(root, file), text: await readFile(file, "utf8") }))); const selected = results.filter((entry) => { const pathName = entry.path.toLowerCase(); const durable = /\/(reference|contract|decision)\//.test(pathName); return durable && (!names.length || names.some((name) => pathName.includes(name) || entry.text.toLowerCase().includes(name))); }).map(({ path: entryPath, text }) => ({ path: entryPath, title: text.match(/^#\s+(.+)$/m)?.[1] ?? path.basename(entryPath, ".md"), excerpt: text.slice(0, 1200) })); return { content: [{ type: "text", text: JSON.stringify({ orientation: selected, guidance: "Read the relevant Project Architecture References, Contracts, and Decisions before graph or direct-code exploration." }, null, 2) }], details: { entries: selected.map((entry) => entry.path) } }; } if (input.action === "search") { const query = (input.query ?? "").toLowerCase(); const results = await Promise.all(files.map(async (file) => ({ path: path.relative(root, file), text: await readFile(file, "utf8") }))); return { content: [{ type: "text", text: JSON.stringify(results.filter((entry) => entry.text.toLowerCase().includes(query)).map(({ path: entryPath, text }) => ({ path: entryPath, excerpt: text.slice(0, 700) })), null, 2) }] }; } if (!input.entryPath) throw new Error("read requires entryPath."); const file = knowledgePath(root, local.docs, input.entryPath); return { content: [{ type: "text", text: await readFile(file, "utf8") }], details: { path: path.relative(root, file) } }; } });
  pi.registerTool({ name: "workspace_knowledge_record", label: "Record Workspace Knowledge", description: "Record factual canonical knowledge. Give a kind, title, and only the factual sections that materially changed; section names and kinds are flexible. Existing headings match case-insensitively, unnamed sections are preserved, and wording-only/format-only changes do nothing. Use only in plan or code, before entering review.", parameters: Type.Object({ kind: Type.String(), title: Type.String(), sections: Type.Record(Type.String(), Type.String()) }), async execute(_id, input, _signal, _update, ctx) { if (isSubagent()) throw new Error("Only the orchestrator may record canonical knowledge."); const root = rootFor(ctx); const state = await loadState(root, sessionId(ctx)); if (!["plan", "code"].includes(state?.phase ?? "")) throw new Error("Knowledge is frozen in review/done; record factual changes before entering review."); const local = await settings(root); if (!input.title.trim()) throw new Error("Provide a knowledge title."); if (!Object.keys(input.sections).length) throw new Error("Provide at least one factual section to record."); const file = path.join(path.resolve(root, local.docs), kindDirectory(input.kind), `${input.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}.md`); let body: string; let changed = false; let created = false; if (!existsSync(file)) { body = emptyKnowledgeEntry(input.kind, input.title, input.sections); changed = true; created = true; } else { body = await readFile(file, "utf8"); for (const [section, content] of Object.entries(input.sections)) { const patched = replaceKnowledgeSection(body, canonicalSection(input.kind, section), content); body = patched.body; changed ||= patched.changed; } } if (changed) { await mkdir(path.dirname(file), { recursive: true }); await writeFile(file, body); } return { content: [{ type: "text", text: changed ? `${created ? "Created" : "Recorded"} factual knowledge.` : "No material knowledge change; left entry untouched." }], details: { path: path.relative(root, file), created, changed, sections: Object.keys(input.sections) } }; } });
  pi.on("tool_call", async (event: any, ctx: ExtensionContext) => { const root = (() => { try { return rootFor(ctx); } catch { return null; } })(); if (!root) return; const local = await settings(root); const docsRoot = path.resolve(root, local.docs); const input = event.input ?? {}; const candidate = typeof input.path === "string" ? path.resolve(root, input.path) : null; if (event.toolName === "subagent" && !input.action && input.artifacts !== false) return { block: true, reason: "Harness subagent launches require artifacts:false so disposable files never enter product repositories." }; if (event.toolName !== "workspace_knowledge" && candidate && inside(docsRoot, candidate)) return { block: true, reason: "Canonical docs are accessible only through workspace_knowledge." }; if (event.toolName === "bash" && typeof input.command === "string" && commandReferencesDocs(input.command, root, local.docs)) return { block: true, reason: "Canonical docs are accessible only through workspace_knowledge." }; const workflow = await loadState(root, sessionId(ctx)); if (["write", "edit", "apply_patch"].includes(event.toolName) && candidate && inside(path.resolve(root, local.projects), candidate) && !isWorker()) return { block: true, reason: "The parent orchestrator never edits projects/**; delegate to impl or impl-lite." }; if (event.toolName === "bash") { const command = String(input.command ?? ""); if (command.includes(".pi/harness/state")) return { block: true, reason: "Workflow state is tool-managed." }; if (!workflow && !isReadOnlyPhaseCommand(command)) return { block: true, reason: "No active workflow: shell is read-only. Start with /workspace:plan." }; if (workflow?.phase === "plan" && !isPlanPhaseCommand(command)) return { block: true, reason: "Plan permits inspection and feat/fix branches only." }; if (workflow && ["review", "done"].includes(workflow.phase) && !isReadOnlyPhaseCommand(command)) return { block: true, reason: `Shell is read-only in ${workflow.phase}.` }; if (workflow?.phase !== "code" && /^gh\s+pr\s+create\b/.test(command)) return { block: true, reason: "PR creation is allowed only in code." }; if (/\bgit\s+push\s+.*--force\b/.test(command)) return { block: true, reason: "Force pushes are blocked." }; } });
}
