import { cp, mkdir, readFile, readdir, rename, unlink, writeFile } from "node:fs/promises";
import { existsSync, readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { ExtensionAPI, ExtensionContext } from "@earendil-works/pi-coding-agent";
import { Text } from "@earendil-works/pi-tui";
import { Type } from "typebox";
import YAML from "yaml";
import { branchName, createWorkflow, isPlanPhaseCommand, isReadOnlyPhaseCommand, transition, type Phase, type WorkflowState } from "./workflow-core.ts";

const PACKAGE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const FLOW_DIR = path.join(".pi", "harness");
const ONBOARDING_FILE = path.join(FLOW_DIR, "onboarding-proposal.json");
const REQUIRED_PI_PACKAGES = ["npm:@gotgenes/pi-permission-system@20.3.0"];
const KINDS: Record<string, string[]> = {
  Decision: ["Context", "Decision", "Alternatives", "Consequences", "Relations"],
  Plan: ["Context", "Scope", "Projects", "Contracts", "Acceptance criteria", "Validation", "Open questions", "Relations"],
  Task: ["Context", "Steps", "Current state", "Blockers", "Relations"],
  Contract: ["Context", "Owner", "Consumers", "Compatibility", "Validation", "Relations"],
  Reference: ["Context", "Observations", "Relations"],
};
type Manifest = { workspace?: { docs_directory?: string; projects_directory?: string }; agents?: Record<string, { model?: string }>; subagents?: { async_by_default?: boolean; tool_description_mode?: "full" | "compact" | "custom"; completion_batch?: boolean; intercom_bridge_mode?: "always" | "fork-only" | "off"; supervisor_output?: "compact" | "full" }; pi?: { packages?: string[] }; permissions?: { default?: "allow" | "ask" | "deny"; shell?: "allow" | "ask" | "deny"; mcp?: "allow" | "ask" | "deny"; external_directories?: "allow" | "ask" | "deny" }; code_graph?: { server_name?: string; command?: string; args?: string[]; lifecycle?: string; idle_timeout?: number }; projects?: Array<{ name: string; path: string; repository?: string; default_branch?: string; depends_on?: string[]; ci?: string[] }> };

function isWorker() { return process.env.PI_SUBAGENT_CHILD === "1" && ["impl", "impl-lite"].includes(process.env.PI_SUBAGENT_CHILD_AGENT ?? ""); }
function isSubagent() { return process.env.PI_SUBAGENT_CHILD === "1"; }
function sessionId(ctx: ExtensionContext) { return process.env.PI_SUBAGENT_PARENT_SESSION || ctx.sessionManager.getSessionId() || "ephemeral"; }
function findRoot(cwd: string) { let current = path.resolve(cwd); while (true) { if (existsSync(path.join(current, "workspace.yaml"))) return current; const parent = path.dirname(current); if (parent === current) throw new Error("Pi Harness is not initialized here. Run the pi-harness initializer before opening Pi."); current = parent; } }
function inside(root: string, target: string) { const relative = path.relative(root, target); return relative === "" || (!relative.startsWith("..") && !path.isAbsolute(relative)); }
async function manifest(root: string): Promise<Manifest> { return YAML.parse(await readFile(path.join(root, "workspace.yaml"), "utf8")) ?? {}; }
function supervisorOutput() { try { const root = findRoot(process.cwd()); return (YAML.parse(readFileSync(path.join(root, "workspace.yaml"), "utf8")) as Manifest)?.subagents?.supervisor_output ?? "compact"; } catch { return "compact"; } }
async function settings(root: string) { const value = await manifest(root); return { docs: value.workspace?.docs_directory ?? "docs", projects: value.workspace?.projects_directory ?? "projects" }; }
function commandReferencesDocs(command: string, root: string, docs: string) { if (command.includes(path.resolve(root, docs))) return true; const escaped = docs.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); return new RegExp(`(^|[\\s"'=])${escaped}(?:/|(?=\\s|$))`).test(command); }
async function version() { return (JSON.parse(await readFile(path.join(PACKAGE_ROOT, "package.json"), "utf8")) as { version: string }).version; }
function externalDirectoryPolicy(settingsFile: string, packages: unknown[], fallback: "allow" | "ask" | "deny" = "ask") {
  const policy: Record<string, "allow" | "ask" | "deny"> = { "*": fallback, "/dev/null": "allow", "/tmp/*": "allow" };
  for (const source of packages) {
    if (typeof source !== "string" || (!source.startsWith(".") && !path.isAbsolute(source))) continue;
    policy[`${path.resolve(path.dirname(settingsFile), source)}/*`] = "allow";
  }
  return policy;
}
function bundledGraphCommand(graph: Manifest["code_graph"] = {}) {
  const legacyCorepack = graph.command === "corepack" && JSON.stringify(graph.args ?? []) === JSON.stringify(["pnpm", "exec", "codebase-memory-mcp"]);
  return legacyCorepack || !graph.command
    ? { command: process.execPath, args: [path.join(PACKAGE_ROOT, "node_modules", "codebase-memory-mcp", "bin.js")] }
    : { command: graph.command, args: graph.args ?? [] };
}

async function sync(root: string) {
  const config = await manifest(root); const packageVersion = await version();
  const managed = path.join(root, ".pi-harness"); await cp(path.join(PACKAGE_ROOT, "templates", "managed"), managed, { recursive: true, force: true });
  await writeFile(path.join(managed, "manifest.json"), JSON.stringify({ package: "pi-harness", version: packageVersion, generatedAt: new Date().toISOString() }, null, 2) + "\n");
  const settingFile = path.join(root, ".pi", "settings.json"); await mkdir(path.dirname(settingFile), { recursive: true });
  const current = existsSync(settingFile) ? JSON.parse(await readFile(settingFile, "utf8")) : {};
  const existingPackages = Array.isArray(current.packages) ? current.packages : [];
  const packages = [...existingPackages]; for (const source of [...REQUIRED_PI_PACKAGES, ...(config.pi?.packages ?? [])]) if (!packages.includes(source)) packages.push(source);
  const configured = config.agents ?? {}; const overrides = current.subagents?.agentOverrides ?? {};
  for (const [name, value] of Object.entries(configured)) if (name !== "orchestrator" && value.model) overrides[name] = { ...(overrides[name] ?? {}), model: value.model };
  await writeFile(settingFile, JSON.stringify({ ...current, ...(packages.length ? { packages } : {}), ...(configured.orchestrator?.model ? { defaultModel: configured.orchestrator.model } : {}), subagents: { ...(current.subagents ?? {}), agentOverrides: overrides } }, null, 2) + "\n");
  const subagents = config.subagents ?? {};
  const subagentConfigFile = path.join(root, ".pi", "extensions", "subagent", "config.json"); await mkdir(path.dirname(subagentConfigFile), { recursive: true });
  const currentSubagentConfig = existsSync(subagentConfigFile) ? JSON.parse(await readFile(subagentConfigFile, "utf8")) : {};
  await writeFile(subagentConfigFile, JSON.stringify({ ...currentSubagentConfig, asyncByDefault: subagents.async_by_default ?? true, toolDescriptionMode: subagents.tool_description_mode ?? "compact", completionBatch: { ...(currentSubagentConfig.completionBatch ?? {}), enabled: subagents.completion_batch ?? true }, control: { ...(currentSubagentConfig.control ?? {}), notifyOn: ["needs_attention"], notifyChannels: ["async"] }, intercomBridge: { ...(currentSubagentConfig.intercomBridge ?? {}), mode: subagents.intercom_bridge_mode ?? "always" } }, null, 2) + "\n");
  const graph = config.code_graph ?? {}; const mcpFile = path.join(root, ".mcp.json"); const mcp = existsSync(mcpFile) ? JSON.parse(await readFile(mcpFile, "utf8")) : {};
  const serverName = graph.server_name ?? "codebase-memory"; const graphProcess = bundledGraphCommand(graph);
  await writeFile(mcpFile, JSON.stringify({ ...mcp, mcpServers: { ...(mcp.mcpServers ?? {}), [serverName]: { ...graphProcess, lifecycle: graph.lifecycle ?? "lazy", idleTimeout: graph.idle_timeout ?? 10 } } }, null, 2) + "\n");
  const permission = JSON.parse(await readFile(path.join(PACKAGE_ROOT, "templates", "permission-config.json"), "utf8")); const p = config.permissions ?? {};
  permission.permission["*"] = p.default ?? "allow"; permission.permission.bash["*"] = p.shell ?? "allow"; permission.permission.mcp["*"] = p.mcp ?? "allow"; permission.permission.external_directory = externalDirectoryPolicy(settingFile, packages, p.external_directories ?? "ask");
  const permissionFile = path.join(root, ".pi", "extensions", "pi-permission-system", "config.json"); await mkdir(path.dirname(permissionFile), { recursive: true }); await writeFile(permissionFile, JSON.stringify(permission, null, 2) + "\n");
  return packageVersion;
}
function statePath(root: string, owner: string) { return path.join(root, FLOW_DIR, "state", `${encodeURIComponent(owner)}.json`); }
async function loadState(root: string, owner: string): Promise<WorkflowState | null> { try { return JSON.parse(await readFile(statePath(root, owner), "utf8")); } catch { return null; } }
async function saveState(root: string, state: WorkflowState) { const file = statePath(root, state.sessionId); await mkdir(path.dirname(file), { recursive: true }); await writeFile(file, JSON.stringify(state, null, 2) + "\n"); }
function render(state: WorkflowState) { return `Workflow ${state.id}: ${state.phase}\nProjects: ${state.projects.join(", ")}\nCI: ${state.checks.ciPassed ? "recorded" : "pending"}; code graph: ${state.checks.codeIndexed ? "recorded" : "pending"}`; }

function parseWorkflowCommands(source: string) { const commands: string[] = []; const lines = source.split("\n"); for (let i = 0; i < lines.length; i++) { const match = lines[i]?.match(/^(\s*)run:\s*(\S.*?)\s*$/); if (!match) continue; if (!/^[|>]$/.test(match[2])) commands.push(match[2]); else { const indent = match[1].length; const body: string[] = []; for (i++; i < lines.length; i++) { const line = lines[i] ?? ""; if (line.trim() && line.match(/^\s*/)?.[0].length <= indent) { i--; break; } if (line.trim() && !line.trimStart().startsWith("#")) body.push(line.trim()); } if (body.length) commands.push(body.join(" && ")); } } return [...new Set(commands)]; }
async function readLocal(dir: string, file: string) { try { return await readFile(path.join(dir, file), "utf8"); } catch { return undefined; } }
async function localCi(dir: string, taskfile?: string, packageJson?: any) { const evidence: string[] = []; const commands: string[] = []; try { const files = await readdir(path.join(dir, ".github", "workflows")); for (const file of files.filter((x) => /(?:ci|check|test).*\.ya?ml$/i.test(x))) { commands.push(...parseWorkflowCommands(await readLocal(dir, path.join(".github", "workflows", file)) ?? "")); evidence.push(`Local CI workflow: .github/workflows/${file}`); } } catch { /* no local workflow */ }
  if (commands.length) return { commands: [...new Set(commands)], evidence, warnings: [] as string[] };
  if (taskfile?.match(/^\s{2,}ci:/m)) return { commands: ["task ci"], evidence: ["Taskfile ci task"], warnings: [] as string[] };
  const scripts = packageJson?.scripts ?? {}; const runner = String(packageJson?.packageManager ?? "").startsWith("pnpm@") ? "pnpm" : "npm run"; if (typeof scripts.ci === "string") return { commands: [`${runner} ci`], evidence: ["package.json ci script"], warnings: [] as string[] };
  const found = ["lint", "format:check", "typecheck", "build", "build-only", "test", "test:unit"].filter((name) => typeof scripts[name] === "string").map((name) => `${runner} ${name}`); return { commands: found, evidence: found.length ? ["package.json scripts: " + found.join(", ")] : [], warnings: [found.length ? "No explicit local CI workflow or ci script; confirm these commands." : "No local CI command was found; set ci explicitly."] };
}
function git(dir: string, args: string[]) { try { return execFileSync("git", ["-C", dir, ...args], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim() || undefined; } catch { return undefined; } }
function githubRepository(remote?: string) { const match = remote?.match(/github\.com[/:]([^/]+\/[^/#]+?)(?:\.git)?$/i); return match?.[1]; }
function pullRequestAvailable(project?: NonNullable<Manifest["projects"]>[number]) { const repository = githubRepository(project?.repository); if (!repository) return false; try { return execFileSync("gh", ["api", `repos/${repository}`, "--jq", ".permissions.push"], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"], timeout: 5000 }).trim() === "true"; } catch { return false; } }
function workspacePullRequestAvailable(root: string) { return pullRequestAvailable({ name: "workspace", path: ".", repository: git(root, ["remote", "get-url", "origin"]), ci: [] }); }
async function discover(root: string) { const config = await manifest(root); const projectsDirectory = config.workspace?.projects_directory ?? "projects"; const projectsRoot = path.resolve(root, projectsDirectory); const entries = await readdir(projectsRoot, { withFileTypes: true }).catch(() => []); const folders = entries.filter((entry) => entry.isDirectory() && !entry.name.startsWith(".")).map((entry) => entry.name); if (!folders.length) throw new Error(`No local projects were found in ${projectsDirectory}/. Clone or initialize repositories there, then run onboarding again.`);
  const discovered = await Promise.all(folders.map(async (name) => { const dir = path.join(projectsRoot, name); if (!(await readdir(dir).catch(() => [])).length) return null; const packageText = await readLocal(dir, "package.json"); let pkg: any = {}; try { pkg = packageText ? JSON.parse(packageText) : {}; } catch { /* surfaced as warning below */ } const taskfile = await readLocal(dir, "Taskfile.yml") ?? await readLocal(dir, "Taskfile.yaml"); const ci = await localCi(dir, taskfile, pkg); const repository = git(dir, ["remote", "get-url", "origin"]); const branch = git(dir, ["branch", "--show-current"]) ?? git(dir, ["symbolic-ref", "--short", "HEAD"]) ?? "main"; const warnings = [...ci.warnings]; if (!existsSync(path.join(dir, ".git"))) warnings.push("Directory is not a Git repository; initialize it before implementation."); if (!repository) warnings.push("No origin remote was found; this is a local-only project."); return { name, ...(repository ? { repository } : {}), path: name, default_branch: branch, ci: ci.commands, evidence: [`Local directory: ${dir}`, ...(repository ? [`Origin remote: ${repository}`] : []), ...ci.evidence], warnings }; }));
  const projects = discovered.filter((project): project is NonNullable<typeof project> => project !== null); if (!projects.length) throw new Error(`No initialized or non-empty local projects were found in ${projectsDirectory}/.`); return projects;
}
function models() { try { return execFileSync("pi", ["--list-models"], { encoding: "utf8" }).split("\n").slice(1).map((line) => line.trim().split(/\s+/)).filter((part) => part.length >= 2).map((part) => `${part[0]}/${part[1]}`); } catch { return []; } }
function modelProposal(list: string[]) { const pick = (terms: string[], fallback?: string) => list.find((item) => terms.some((term) => item.toLowerCase().includes(term))) ?? fallback ?? list[0]; const main = pick(["/main", "/max", "/auto"]); return { orchestrator: { model: main }, impl: { model: pick(["/code", "coder"], main) }, "impl-lite": { model: pick(["code-lite", "fast", "lite"], main) }, explore: { model: pick(["/main", "/chat", "/auto"], main) } }; }
function onboardingManifest(current: string, projects: any[], available: string[]) { const value: any = YAML.parse(current) ?? {}; value.version ??= 1; value.workspace ??= { docs_directory: "docs", projects_directory: "projects" }; value.agents = modelProposal(available); value.projects = projects.map((project) => ({ name: project.name, ...(project.repository ? { repository: project.repository } : {}), path: project.path, default_branch: project.default_branch, depends_on: [], ci: project.ci })); return YAML.stringify(value); }
function validateManifest(text: string) { const value = YAML.parse(text) as Manifest; if (!value || !Array.isArray(value.projects)) throw new Error("The proposal must be a complete workspace.yaml with a projects array."); for (const project of value.projects) if (!project?.name || !project.path || !Array.isArray(project.ci) || !project.ci.every((command) => typeof command === "string" && command.trim()) || (project.repository !== undefined && typeof project.repository !== "string")) throw new Error("Every project requires name, path, and a ci array of non-empty command strings; repository is optional."); }
function proposalToken(text: string) { return createHash("sha256").update(text).digest("hex").slice(0, 24); }
async function stageProposal(root: string, text: string) { validateManifest(text); const file = path.join(root, ONBOARDING_FILE); await mkdir(path.dirname(file), { recursive: true }); await writeFile(file, JSON.stringify({ baseManifest: await readFile(path.join(root, "workspace.yaml"), "utf8"), manifest: text }, null, 2) + "\n"); }
async function applyProposal(root: string) { const file = path.join(root, ONBOARDING_FILE); const proposal = JSON.parse(await readFile(file, "utf8")); if (await readFile(path.join(root, "workspace.yaml"), "utf8") !== proposal.baseManifest) throw new Error("workspace.yaml changed after the proposal was staged. Re-run onboarding."); validateManifest(proposal.manifest); await writeFile(path.join(root, "workspace.yaml"), proposal.manifest); await sync(root); await unlink(file); }

function normal(text: string) { return text.replace(/\s+/g, " ").trim(); }
async function entries(dir: string) { const files = await readdir(dir, { withFileTypes: true }).catch(() => []); const all = await Promise.all(files.map(async (file) => { const target = path.join(dir, file.name); return file.isDirectory() ? entries(target) : file.isFile() && file.name.endsWith(".md") ? [target] : []; })); return all.flat(); }
function knowledgePath(root: string, docs: string, entryPath: string) { const target = path.resolve(root, entryPath); const base = path.resolve(root, docs); if (!inside(base, target)) throw new Error("Knowledge entry path escapes docs/."); return target; }
function validateKnowledge(kind: string, title: string, body: string) { if (!KINDS[kind]) throw new Error("Unknown knowledge kind."); if (!title.trim() || !body.includes(`# ${title.trim()}`)) throw new Error("Knowledge must contain an H1 matching title."); for (const heading of KINDS[kind]) if (!body.includes(`## ${heading}`)) throw new Error(`Knowledge is missing required section: ${heading}`); }
function sectionPatch(body: string, section: string, expected: string, next: string) { const heading = new RegExp(`^## ${section.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\r?\\n`, "m"); const match = heading.exec(body); if (!match || match.index === undefined) throw new Error(`Section not found: ${section}`); const start = match.index + match[0].length; const following = /^## .+$/gm; following.lastIndex = start; const nextHeading = following.exec(body); const end = nextHeading?.index ?? body.length; const current = body.slice(start, end); if (current.trim() !== expected.trim()) throw new Error(`Section changed since it was read: ${section}.`); if (normal(current) === normal(next)) return { body, changed: false }; return { body: `${body.slice(0, start)}${next.trim()}\n\n${body.slice(end)}`, changed: true }; }
function normalizedSection(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, "").trim(); }
function cleanSection(value: string) { const section = value.replace(/[\r\n#]+/g, " ").trim(); if (!section) throw new Error("Knowledge section names cannot be empty."); return section; }
function canonicalKind(kind: string) { const cleaned = cleanSection(kind); return Object.keys(KINDS).find((candidate) => normalizedSection(candidate) === normalizedSection(cleaned)) ?? cleaned; }
function kindDirectory(kind: string) { return canonicalKind(kind).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "reference"; }
function canonicalSection(kind: string, section: string) { const cleaned = cleanSection(section); return KINDS[canonicalKind(kind)]?.find((candidate) => normalizedSection(candidate) === normalizedSection(cleaned)) ?? cleaned; }
function emptyKnowledgeEntry(kind: string, title: string, sections: Record<string, string>) { const canonical = canonicalKind(kind); const supplied = Object.entries(sections).map(([section, content]) => [canonicalSection(canonical, section), content] as const); const required = KINDS[canonical]; if (!required) return `# ${title.trim()}\n\n${supplied.map(([section, content]) => `## ${section}\n\n${content.trim()}`).join("\n\n")}\n`; const known = new Map(supplied.filter(([section]) => required.includes(section))); const extra = supplied.filter(([section]) => !required.includes(section)); const body = `# ${title.trim()}\n\n${required.map((section) => `## ${section}\n\n${known.get(section)?.trim() ?? ""}`).join("\n\n")}${extra.length ? `\n\n${extra.map(([section, content]) => `## ${section}\n\n${content.trim()}`).join("\n\n")}` : ""}\n`; validateKnowledge(canonical, title, body); return body; }
function replaceKnowledgeSection(body: string, section: string, next: string) { const requested = cleanSection(section); const headings = [...body.matchAll(/^## (.+)$/gm)]; const found = headings.find((heading) => normalizedSection(heading[1]!) === normalizedSection(requested)); if (!found || found.index === undefined) { if (!next.trim()) return { body, changed: false }; return { body: `${body.trimEnd()}\n\n## ${requested}\n\n${next.trim()}\n`, changed: true }; } const start = found.index + found[0].length + 1; const nextHeading = headings.find((heading) => (heading.index ?? 0) > found.index!); const end = nextHeading?.index ?? body.length; const current = body.slice(start, end); if (normal(current) === normal(next)) return { body, changed: false }; return { body: `${body.slice(0, start)}\n${next.trim()}\n\n${body.slice(end)}`, changed: true }; }

export default function workspaceFlow(pi: ExtensionAPI) {
  const rootFor = (ctx: ExtensionContext) => findRoot(ctx.cwd); const approvals = new Set<string>();
  pi.registerMessageRenderer?.("subagent_supervisor_request", (message: any, { expanded }: { expanded: boolean }, theme: any) => { if (supervisorOutput() === "full") return new Text(String(message.content)); const details = message.details as { reason?: string; agent?: string; runId?: string; childIndex?: number } | undefined; const body = String(message.content).split(/\n\s*\n/).slice(-1)[0]?.trim() || "No details supplied."; const label = details?.reason === "need_decision" ? "needs a decision" : details?.reason === "interview_request" ? "requests input" : "update"; const title = `${details?.agent ?? "subagent"} ${label}: ${body}`; const meta = `run ${details?.runId ?? "unknown"}, child ${details?.childIndex ?? "?"}`; return new Text(expanded ? `${title}\n${theme.fg("dim", meta)}` : title); });
  pi.events?.on?.("ask:answered", (raw) => { const value = raw as any; const token = value.context?.match(/pi-harness:onboarding-apply:([a-f0-9]{24})/)?.[1]; if (token && value.response?.kind === "selection" && value.response.selections?.includes("Apply now")) approvals.add(token); });
  const send = (text: string) => pi.sendUserMessage(text, { deliverAs: "followUp" });
  pi.registerCommand("workspace:sync", { description: "Synchronize generated settings from workspace.yaml", handler: async (_args, ctx) => { const v = await sync(rootFor(ctx)); ctx.ui.notify(`Synced pi-harness ${v}.`, "info"); } });
  pi.registerCommand("workspace:onboard", { description: "Analyze local projects and guide workspace configuration", handler: async (args, ctx) => { if (isSubagent()) throw new Error("Only the orchestrator may onboard."); if (args.trim()) throw new Error("Onboarding takes no sources. Set up repositories under projects/ first."); await send("Start local-first workspace onboarding. Load workspace-onboarding and ask-user skills. Call workspace_onboarding action=discover with no source arguments. Analyze only local projects/*; never call GitHub, web, gh, or remote inspection. Use ask_user to confirm CI for each included project, dependency relationships, and model pins; do not infer those preferences. Ask one focused decision at a time. Present the complete workspace.yaml, immediately stage that exact proposal with workspace_onboarding action=propose, then ask the single final token-bound Apply now / Revise proposal / Cancel question. Never ask any earlier approval question, and never create or clone repositories during onboarding."); } });
  pi.registerCommand("workspace:plan", { description: "Start user-controlled planning", handler: async (subject, ctx) => { const root = rootFor(ctx); const owner = sessionId(ctx); if (await loadState(root, owner)) throw new Error("This session already owns a workflow."); const state = createWorkflow(subject, owner); await saveState(root, state); pi.setSessionName(state.subject); await send(`The workflow is in plan phase. Immediately load workspace-development-loop and workspace-knowledge-protocol; they are the workflow authority—never inspect node_modules, .pi internals, or package source to rediscover this workflow. Required order: (1) call workspace_knowledge orientation, then search/read relevant project architecture, contracts, decisions, and subject context; (2) inspect the available codebase-memory MCP tools and use the graph for structural discovery; (3) use targeted direct reads only for code facts not answered by knowledge or graph. After that evidence, choose a concise semantic branch name: an appropriate work-type prefix (for example feat, fix, docs, refactor, test, ci, build, chore, perf, or style) plus the shortest clear description of the actual outcome. This may mirror Conventional Commit types, but branch naming is a Harness convention, not the Conventional Commits specification. Do not mechanically slug the user’s request; name the actual outcome. Before any knowledge write, create and record that branch in the coordination root and each affected product. The fallback suggestion is ${branchName(state.subject)}, but replace it whenever the evidence supports a clearer name. Do not replace unfamiliar structural exploration with broad parent file reading: launch the named explore agent via subagent (never generic delegate), async:true, clarify:false, context:fresh, artifacts:false, acceptance:{level:none,reason:"Pi Harness owns worker evidence, CI, and review."}, and with no cwd override, for every task that is not narrow and graph-known. Skip explore only when the graph and handoff already answer the narrow question. Parent may read non-doc workspace/project files and create suggested branches, but must never edit product files; docs are only through workspace_knowledge. Create durable Plan and Task entries with workspace_knowledge_record, and create/update a Reference titled Project architecture — <project> for every affected project: purpose, ownership, entry points, key modules, flows, interfaces, configuration, validation, and graph anchors. Record factual sections in natural names, never a hand-formatted Markdown body; matching headings update and new factual headings are added, preserving everything else.`); } });
  pi.registerCommand("workspace:code", { description: "User-authorize plan/review to code", handler: async (feedback, ctx) => { const root = rootFor(ctx); const state = await loadState(root, sessionId(ctx)); if (!state) throw new Error("No active workflow."); await saveState(root, transition(state, "code")); await send(`The workflow is now in code. Delegate every product edit with the pi-subagents subagent tool. Route a one-file documentation, test, config, or localized implementation change to impl-lite; use impl only for multi-file, cross-project, contract, or genuinely complex work. Never use generic delegate, an intercom-only child, or foreground parallel execution. Launch async:true, clarify:false, context:fresh, artifacts:false, acceptance:{level:none,reason:"Pi Harness owns worker evidence, CI, and review."}, and NO cwd override so child Pi loads this workspace's tools. State the target checkout path in the handoff and have the worker operate beneath projects/. Include acceptance criteria, graph evidence, and configured CI, but never tell workers to read canonical docs or call workspace knowledge. One writer per checkout at a time. Continue independent orchestration work; when waiting is necessary, use wait rather than status-polling. The resolved workspace.yaml model pins for impl and impl-lite apply to those exact agent names. ${feedback.trim() ? `Address: ${feedback.trim()}` : "Implement the approved plan."} Before review, record material architecture/contract/decision outcomes, commit tracked coordination changes on the workspace branch, and create/record a workspace PR if its GitHub origin has usable gh access. Collect concise structured handoffs, run configured CI, update canonical knowledge, push branches and create PRs only where available, then record evidence and enter review.`); } });
  pi.registerCommand("workspace:done", { description: "User-authorize review closure", handler: async (_args, ctx) => { const root = rootFor(ctx); const state = await loadState(root, sessionId(ctx)); if (!state) throw new Error("No active workflow."); await saveState(root, transition(state, "done")); await send("The workflow is done. Do not edit, merge, create PRs, or write knowledge. Summarize PRs in dependency order and offer cleanup only after confirmed merges."); } });
  pi.registerCommand("workspace:status", { description: "Show workflow state", handler: async (_args, ctx) => ctx.ui.notify((await loadState(rootFor(ctx), sessionId(ctx))) ? render((await loadState(rootFor(ctx), sessionId(ctx)))!) : "No active workflow.", "info") });
  pi.registerCommand("workspace:continue", { description: "Rebind a saved workflow", handler: async (id, ctx) => { const root = rootFor(ctx); const owner = sessionId(ctx); const directory = path.join(root, FLOW_DIR, "state"); const states = await Promise.all((await readdir(directory).catch(() => [])).filter((x) => x.endsWith(".json")).map(async (x) => JSON.parse(await readFile(path.join(directory, x), "utf8")) as WorkflowState)); const state = states.find((x) => x.id.startsWith(id.trim()) || x.sessionId.startsWith(id.trim())); if (!state) throw new Error("No matching workflow."); await saveState(root, { ...state, sessionId: owner, updatedAt: new Date().toISOString() }); await rename(statePath(root, state.sessionId), `${statePath(root, state.sessionId)}.rebound`).catch(() => undefined); } });

  pi.registerTool({ name: "workspace_workflow", label: "Workspace Workflow", description: "Read or record workflow state; review requires a committed coordination workspace, CI, graph evidence, and PRs wherever GitHub access is available.", parameters: Type.Object({ action: Type.Union([Type.Literal("status"), Type.Literal("update"), Type.Literal("record_checks"), Type.Literal("enter_review")]), projects: Type.Optional(Type.Array(Type.String())), branches: Type.Optional(Type.Record(Type.String(), Type.String())), pullRequests: Type.Optional(Type.Record(Type.String(), Type.Number())), notes: Type.Optional(Type.Array(Type.String())), ciPassed: Type.Optional(Type.Boolean()), codeIndexed: Type.Optional(Type.Boolean()) }), async execute(_id, input, _signal, _update, ctx) { const root = rootFor(ctx); const state = await loadState(root, sessionId(ctx)); if (!state) throw new Error("No active workflow."); if (input.action === "status") return { content: [{ type: "text", text: render(state) }], details: state }; if (isSubagent()) throw new Error("Only the orchestrator updates workflow state."); if (input.action === "enter_review") { if (!state.checks.ciPassed || !state.checks.codeIndexed) throw new Error("CI and code-index checks must be recorded before review."); const workspaceBranch = git(root, ["branch", "--show-current"]); if (workspaceBranch === "main") throw new Error("Commit coordination changes on their workflow branch, not main, before review."); const pendingWorkspaceChanges = git(root, ["status", "--porcelain"]); if (pendingWorkspaceChanges) throw new Error("Commit all non-ignored coordination-workspace changes before review."); const configured = (await manifest(root)).projects ?? []; const required = state.projects.filter((name) => name !== "workspace" && pullRequestAvailable(configured.find((project) => project.name === name))); if (workspacePullRequestAvailable(root)) required.unshift("workspace"); const missing = required.filter((name) => !state.pullRequests[name]); if (missing.length) throw new Error(`Open and record PRs before review. GitHub PR access is available for: ${missing.join(", ")}`); const next = transition(state, "review"); await saveState(root, next); return { content: [{ type: "text", text: render(next) }], details: { ...next, pullRequestsRequired: required } }; } if (!["plan", "code"].includes(state.phase)) throw new Error(`Cannot record workflow evidence in ${state.phase}.`); const next = { ...state, projects: input.projects ? [...new Set(["workspace", ...input.projects])] : state.projects, branches: input.branches ?? state.branches, pullRequests: input.pullRequests ?? state.pullRequests, notes: input.notes ?? state.notes, checks: { ciPassed: input.ciPassed ?? state.checks.ciPassed, codeIndexed: input.codeIndexed ?? state.checks.codeIndexed }, updatedAt: new Date().toISOString() }; await saveState(root, next); return { content: [{ type: "text", text: render(next) }], details: next }; } });
  pi.registerTool({ name: "workspace_onboarding", label: "Workspace Onboarding", description: "Analyze local projects and stage/apply a reviewed workspace manifest.", parameters: Type.Object({ action: Type.Union([Type.Literal("discover"), Type.Literal("propose"), Type.Literal("apply")]), manifest: Type.Optional(Type.String()), approvalToken: Type.Optional(Type.String()) }), async execute(_id, input, _signal, _update, ctx) { if (isSubagent()) throw new Error("Only the orchestrator may onboard."); const root = rootFor(ctx); if (input.action === "discover") { const projects = await discover(root); const available = models(); const text = onboardingManifest(await readFile(path.join(root, "workspace.yaml"), "utf8"), projects, available); return { content: [{ type: "text", text: JSON.stringify({ proposed_workspace_yaml: text, projects, available_models: available, suggested_agents: modelProposal(available) }, null, 2) }], details: { manifest: text, repositories: projects, models: available } }; } if (input.action === "propose") { if (!input.manifest?.trim()) throw new Error("propose requires complete workspace.yaml."); await stageProposal(root, input.manifest); const token = proposalToken(input.manifest); return { content: [{ type: "text", text: `Staged proposal. Ask ask_user Apply now / Revise proposal / Cancel using context pi-harness:onboarding-apply:${token}; only then call apply with approvalToken.` }], details: { approvalToken: token } }; } const proposal = JSON.parse(await readFile(path.join(root, ONBOARDING_FILE), "utf8")); const token = proposalToken(proposal.manifest); if (!input.approvalToken || input.approvalToken !== token || !approvals.delete(token)) throw new Error("Applying onboarding requires a fresh ask_user response selecting Apply now for this exact proposal."); await applyProposal(root); return { content: [{ type: "text", text: "Applied workspace onboarding proposal and synchronized generated configuration." }], details: { applied: true } }; } });
  pi.registerTool({ name: "workspace_knowledge", label: "Workspace Knowledge", description: "Orient to, search, and read canonical workspace knowledge. Begin planning with orientation; use workspace_knowledge_record for every normal write.", parameters: Type.Object({ action: Type.Union([Type.Literal("orientation"), Type.Literal("search"), Type.Literal("read")]), query: Type.Optional(Type.String()), entryPath: Type.Optional(Type.String()), projects: Type.Optional(Type.Array(Type.String())) }), async execute(_id, input, _signal, _update, ctx) { if (isSubagent()) throw new Error("Only the orchestrator may access canonical knowledge."); const root = rootFor(ctx); const local = await settings(root); const docsRoot = path.resolve(root, local.docs); const files = await entries(docsRoot); if (input.action === "orientation") { const names = (input.projects ?? []).map((project) => project.toLowerCase()); const results = await Promise.all(files.map(async (file) => ({ path: path.relative(root, file), text: await readFile(file, "utf8") }))); const selected = results.filter((entry) => { const pathName = entry.path.toLowerCase(); const durable = /\/(reference|contract|decision)\//.test(pathName); return durable && (!names.length || names.some((name) => pathName.includes(name) || entry.text.toLowerCase().includes(name))); }).map(({ path: entryPath, text }) => ({ path: entryPath, title: text.match(/^#\s+(.+)$/m)?.[1] ?? path.basename(entryPath, ".md"), excerpt: text.slice(0, 1200) })); return { content: [{ type: "text", text: JSON.stringify({ orientation: selected, guidance: "Read the relevant Project Architecture References, Contracts, and Decisions before graph or direct-code exploration." }, null, 2) }], details: { entries: selected.map((entry) => entry.path) } }; } if (input.action === "search") { const query = (input.query ?? "").toLowerCase(); const results = await Promise.all(files.map(async (file) => ({ path: path.relative(root, file), text: await readFile(file, "utf8") }))); return { content: [{ type: "text", text: JSON.stringify(results.filter((entry) => entry.text.toLowerCase().includes(query)).map(({ path: entryPath, text }) => ({ path: entryPath, excerpt: text.slice(0, 700) })), null, 2) }] }; } if (!input.entryPath) throw new Error("read requires entryPath."); const file = knowledgePath(root, local.docs, input.entryPath); return { content: [{ type: "text", text: await readFile(file, "utf8") }], details: { path: path.relative(root, file) } }; } });
  pi.registerTool({ name: "workspace_knowledge_record", label: "Record Workspace Knowledge", description: "Record factual canonical knowledge. Give a kind, title, and only the factual sections that materially changed; section names and kinds are flexible. Existing headings match case-insensitively, unnamed sections are preserved, and wording-only/format-only changes do nothing. Use only in plan or code, before entering review.", parameters: Type.Object({ kind: Type.String(), title: Type.String(), sections: Type.Record(Type.String(), Type.String()) }), async execute(_id, input, _signal, _update, ctx) { if (isSubagent()) throw new Error("Only the orchestrator may record canonical knowledge."); const root = rootFor(ctx); const state = await loadState(root, sessionId(ctx)); if (!["plan", "code"].includes(state?.phase ?? "")) throw new Error("Knowledge is frozen in review/done; record factual changes before entering review."); const local = await settings(root); if (!input.title.trim()) throw new Error("Provide a knowledge title."); if (!Object.keys(input.sections).length) throw new Error("Provide at least one factual section to record."); const file = path.join(path.resolve(root, local.docs), kindDirectory(input.kind), `${input.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}.md`); let body: string; let changed = false; let created = false; if (!existsSync(file)) { body = emptyKnowledgeEntry(input.kind, input.title, input.sections); changed = true; created = true; } else { body = await readFile(file, "utf8"); for (const [section, content] of Object.entries(input.sections)) { const patched = replaceKnowledgeSection(body, canonicalSection(input.kind, section), content); body = patched.body; changed ||= patched.changed; } } if (changed) { await mkdir(path.dirname(file), { recursive: true }); await writeFile(file, body); } return { content: [{ type: "text", text: changed ? `${created ? "Created" : "Recorded"} factual knowledge.` : "No material knowledge change; left entry untouched." }], details: { path: path.relative(root, file), created, changed, sections: Object.keys(input.sections) } }; } });
  pi.on("tool_call", async (event: any, ctx: ExtensionContext) => { const root = (() => { try { return rootFor(ctx); } catch { return null; } })(); if (!root) return; const local = await settings(root); const docsRoot = path.resolve(root, local.docs); const input = event.input ?? {}; const candidate = typeof input.path === "string" ? path.resolve(root, input.path) : null; if (event.toolName === "subagent" && !input.action && input.artifacts !== false) return { block: true, reason: "Harness subagent launches require artifacts:false so disposable files never enter product repositories." }; if (event.toolName !== "workspace_knowledge" && candidate && inside(docsRoot, candidate)) return { block: true, reason: "Canonical docs are accessible only through workspace_knowledge." }; if (event.toolName === "bash" && typeof input.command === "string" && commandReferencesDocs(input.command, root, local.docs)) return { block: true, reason: "Canonical docs are accessible only through workspace_knowledge." }; const workflow = await loadState(root, sessionId(ctx)); if (["write", "edit", "apply_patch"].includes(event.toolName) && candidate && inside(path.resolve(root, local.projects), candidate) && !isWorker()) return { block: true, reason: "The parent orchestrator never edits projects/**; delegate to impl or impl-lite." }; if (event.toolName === "bash") { const command = String(input.command ?? ""); if (command.includes(".pi/harness/state")) return { block: true, reason: "Workflow state is tool-managed." }; if (!workflow && !isReadOnlyPhaseCommand(command)) return { block: true, reason: "No active workflow: shell is read-only. Start with /workspace:plan." }; if (workflow?.phase === "plan" && !isPlanPhaseCommand(command)) return { block: true, reason: "Plan permits inspection and feat/fix branches only." }; if (workflow && ["review", "done"].includes(workflow.phase) && !isReadOnlyPhaseCommand(command)) return { block: true, reason: `Shell is read-only in ${workflow.phase}.` }; if (workflow?.phase !== "code" && /^gh\s+pr\s+create\b/.test(command)) return { block: true, reason: "PR creation is allowed only in code." }; if (/\bgit\s+push\s+.*--force\b/.test(command)) return { block: true, reason: "Force pushes are blocked." }; } });
}
